### ISSUE TITLE
Can this be used in Angular?

### ISSUE THREAD

**Issue by maitriyogin** [riga/jclass#3]
Hi,
I started off using Resigs version in an angular app which worked/s great.
I then tried bringing in jclass but get lots of errors, with angulars._extend method.
I'm wondering if jclass is overriding angulars own _exclude ?
/Stephen.

**Comment by riga** [comment]
Hey Stephen,

can you provide me with a minimal version of your script? I'll check that and let you know!

Best,
Marcel

**Comment by maitriyogin** [comment]
Sure, I'll try and get something together soonish..
/stephen

**Comment by riga** [comment]
Thanks!

**Comment by maitriyogin** [comment]
Hi Marcel,
it's a false alarm.. intellij had decided to refactor some other .extend methods one of these being angular.extend, to angular._extend ...
It's now working as expected, keep up the good work!
Cheers,
Stephen.

**Comment by riga** [comment]
Thanks!

No problem ;) Let me know if something doesn't work as expected.
